# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 200  # Hz

    rv_2frb_d_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

rv_2frb_d_arm_controller:
  ros__parameters:
    joints:
      - J1
      - J2
      - J3
      - J4
      - J5
      - J6
    command_interfaces:
      - position
    state_interfaces:
      - position      
    state_publish_rate: 200.0
    action_monitor_rate: 20.0